/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2021-06-15 11:17:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gx.domain.*;

public final class personalCenter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.gx.domain");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>个人中心</title>\r\n");
      out.write("\r\n");

User user = (User) request.getSession().getAttribute("user"); 
String name = user.getName();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 导入easyui的资源文件 -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/jquery.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"static/easyui/themes/icon.css\">\r\n");
      out.write("        <link id=\"themeLink\" rel=\"stylesheet\" type=\"text/css\" href=\"static/easyui/themes/default/easyui.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"static/css/zTreeStyle/zTreeStyle.css\">\r\n");
      out.write("        <script src=\"static/js/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #sidebar {\r\n");
      out.write("            background-color: #000;\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 750px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin: 15px 0px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #sidebar span {\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 5px 0px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            line-height: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #header {\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background-color: #277de6;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #header span {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            float: left;\r\n");
      out.write("            border: 1.5px solid grey;\r\n");
      out.write("            width: 210px;\r\n");
      out.write("            height: 37px;\r\n");
      out.write("            line-height: 37px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #function:hover {\r\n");
      out.write("            background: #8f949a;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #content {\r\n");
      out.write("            float:left;\r\n");
      out.write("            display:block;\r\n");
      out.write("            width:1275px;\r\n");
      out.write("            height:710px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #info {\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #function2 {\r\n");
      out.write("            margin: 0 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #function2>div {\r\n");
      out.write("            width: 650px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            margin: 25px 0;\r\n");
      out.write("            font-size: 19px;\r\n");
      out.write("            line-height: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"sidebar\">\r\n");
      out.write("        <sapn>\r\n");
      out.write("            <h1>导航</h1>\r\n");
      out.write("        </sapn>\r\n");
      out.write("        <span><a href=\"index\" style=\"color:white;text-decoration:none;\">首页</a></span>\r\n");
      out.write("        <span><a href=\"staffAdminister\" style=\"color:white;text-decoration:none;\">人事管理</a></span>\r\n");
      out.write("        <span><a href=\"attendanceCount\" style=\"color:white;text-decoration:none;\">考勤统计</a></span>\r\n");
      out.write("        <span><a href=\"salaryAdminister\" style=\"color:white;text-decoration:none;\">工资管理</a></span>\r\n");
      out.write("        <span style=\"background-color: #277de6\">个人中心</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <span id=\"function\">首页</span>\r\n");
      out.write("        <span id=\"function\">人事管理</span>\r\n");
      out.write("        <span id=\"function\">考勤统计</span>\r\n");
      out.write("        <span id=\"function\">工资管理</span>\r\n");
      out.write("        <span id=\"function\">个人中心</span>\r\n");
      out.write("        <span style=\"border-right: 0px;\">欢迎您，");
      out.print(name );
      out.write("</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <div id=\"info\">\r\n");
      out.write("            <div style=\"display:inline-block;float: left;margin: 20px;\"><img src=\"static/images/ahu.jpg\" style=\"height: 200px;width: 200px;\"></div>\r\n");
      out.write("            <div style=\"width: 400px;border: 1px solid grey;height: 40px;display: inline-block;text-align: center;line-height: 40px;margin: 39px 0;margin-right: 400px;\">");
      out.print(user.getName() );
      out.write("</div>\r\n");
      out.write("            <div style=\"width: 400px;border: 1px solid grey;height: 40px;display: inline-block;text-align: center;line-height: 40px;margin: 30px 0;\">");
      out.print(user.getAccount() );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"function2\">\r\n");
      out.write("            <div><button id=\"btn1\" style=\"display: block;width: 100%;height: 100%;\">修改密码</button></div>\r\n");
      out.write("            <div><button id=\"btn2\" style=\"display: block;width: 100%;height: 100%;\">意见反馈</button></div>\r\n");
      out.write("            <div><button id=\"btn3\" style=\"display: block;width: 100%;height: 100%;\">关于我们</button></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"win1\" class=\"easyui-window\" title=\"修改密码\" style=\"width:400px;height:400px\" data-options=\"iconCls:'icon-save',modal:true,closed:true\"> \r\n");
      out.write("            <form method=\"post\" id=\"editForm1\"> \r\n");
      out.write("                修改的密码：<input type=\"text\" name=\"password\" class=\"easyui-validatebox\" data-options=\"required:true\"/><br/> \r\n");
      out.write("                <a id=\"modify1\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save'\">修改</a> \r\n");
      out.write("            </form>            \r\n");
      out.write("        </div> \r\n");
      out.write("        \r\n");
      out.write("        <div id=\"win2\" class=\"easyui-window\" title=\"反馈信息\" style=\"width:400px;height:400px\" data-options=\"iconCls:'icon-save',modal:true,closed:true\"> \r\n");
      out.write("            <form method=\"post\" id=\"editForm2\"> \r\n");
      out.write("                反馈信息：<br><textarea></textarea><br/> \r\n");
      out.write("                <a id=\"modify2\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save'\">提交</a> \r\n");
      out.write("            </form>            \r\n");
      out.write("        </div> \r\n");
      out.write("        \r\n");
      out.write("        <div id=\"win3\" class=\"easyui-window\" title=\"关于我们\" style=\"width:400px;height:400px\" data-options=\"iconCls:'icon-save',modal:true,closed:true\"> \r\n");
      out.write("            <div style=\"display:block;\">小组成员:<br>董艳民、谢东阳、杨富超、王相、张婷婷、王志诚</div>            \r\n");
      out.write("        </div> \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t    $(\"#btn1\").click(function(){\r\n");
      out.write("\t    \t$(\"#win1\").window(\"open\"); \r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\"#btn2\").click(function(){\r\n");
      out.write("\t    \t$(\"#win2\").window(\"open\"); \r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("\t    $(\"#btn3\").click(function(){\r\n");
      out.write("\t    \t$(\"#win3\").window(\"open\"); \r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\"#modify1\").click(function(){\r\n");
      out.write("\t        $(\"#editForm1\").form(\"submit\",{\r\n");
      out.write("\t            //url: 提交到后台的地址\r\n");
      out.write("\t            url:\"modifyPassword\",\r\n");
      out.write("\t            //onSubmit: 表单提交前的回调函数，true：提交表单   false：不提交表单\r\n");
      out.write("\t            onSubmit:function(){\r\n");
      out.write("\t                //判断表单的验证是否都通过了\r\n");
      out.write("\t                return $(\"#editForm\").form(\"validate\");\r\n");
      out.write("\t            },\r\n");
      out.write("\t            //success:服务器执行完毕回调函数\r\n");
      out.write("\t            success:function(data){ //data: 服务器返回的数据，类型字符串类\r\n");
      out.write("\t                //要求Controller返回的数据格式：  \r\n");
      out.write("\t                //成功：{success:true} 失败:{success:false,msg:错误信息}\r\n");
      out.write("\t                \r\n");
      out.write("\t                //把data字符串类型转换对象类型\r\n");
      out.write("\t                data = eval(\"(\"+data+\")\");\r\n");
      out.write("\t                \r\n");
      out.write("\t                if(data.success){\r\n");
      out.write("\t                    //关闭窗口\r\n");
      out.write("\t                    $(\"#win1\").window(\"close\");               \r\n");
      out.write("\t                    $.messager.alert(\"提示\",\"修改成功\",\"info\");\r\n");
      out.write("\t                }else{\r\n");
      out.write("\t                    $.messager.alert(\"提示\",\"修改失败：\"+data.msg,\"error\");\r\n");
      out.write("\t                }\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\"#modify2\").click(function(){\r\n");
      out.write("\t    \t$.messager.alert(\"提示\",\"反馈成功\",\"info\");\r\n");
      out.write("\t    \t$(\"#win2\").window(\"close\");  \r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
