/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2021-06-29 03:31:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gx.domain.*;

public final class salaryAdminister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.gx.domain");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>工资管理</title>\r\n");
      out.write("\r\n");

User user = (User) request.getSession().getAttribute("user"); 
String name = user.getName();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 导入easyui的资源文件 -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/jquery.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"static/easyui/themes/icon.css\">\r\n");
      out.write("        <link id=\"themeLink\" rel=\"stylesheet\" type=\"text/css\" href=\"static/easyui/themes/default/easyui.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"static/css/zTreeStyle/zTreeStyle.css\">\r\n");
      out.write("        <script src=\"static/js/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #sidebar {\r\n");
      out.write("            background-color: #000;\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 750px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin: 15px 0px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #sidebar span {\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 5px 0px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            line-height: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #header {\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background-color: #277de6;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #header span {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            float: left;\r\n");
      out.write("            border: 1.5px solid grey;\r\n");
      out.write("            width: 210px;\r\n");
      out.write("            height: 37px;\r\n");
      out.write("            line-height: 37px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #function:hover {\r\n");
      out.write("            background: #8f949a;\r\n");
      out.write("        }\r\n");
      out.write("        #content {\r\n");
      out.write("            float:left;\r\n");
      out.write("            display:block;\r\n");
      out.write("            width:1275px;\r\n");
      out.write("            height:710px;\r\n");
      out.write("        }\r\n");
      out.write("        #content #title{\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("            font-size: 26px;\r\n");
      out.write("            margin-top: 75px;\r\n");
      out.write("            margin-left: 15px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        #lists {\r\n");
      out.write("            display:block;\r\n");
      out.write("            width:1000px;\r\n");
      out.write("            margin-left: 40px;\r\n");
      out.write("            margin-top: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .p {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            float: left;\r\n");
      out.write("            border: 1.5px solid grey;\r\n");
      out.write("            width: 210px;\r\n");
      out.write("            height: 37px;\r\n");
      out.write("            line-height: 37px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .p:active{\r\n");
      out.write("           background-color: #277de6; \r\n");
      out.write("        }\r\n");
      out.write("        .table_p{\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            width:850px;\r\n");
      out.write("            text-align:center;\r\n");
      out.write("            border-width:2px;\r\n");
      out.write("            border-style:solid;\r\n");
      out.write("            margin-top: 160px;\r\n");
      out.write("            margin-left: 250px;\r\n");
      out.write("            color:grey;\r\n");
      out.write("        }\r\n");
      out.write("        .th_p{\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            border-width:3px;\r\n");
      out.write("            border-style:solid;\r\n");
      out.write("            max-width: 100px;\r\n");
      out.write("            color:grey;\r\n");
      out.write("        }\r\n");
      out.write("        .td_p{\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            border-width:3px;\r\n");
      out.write("            border-style:solid;\r\n");
      out.write("            max-width: 100px;\r\n");
      out.write("            color:grey;\r\n");
      out.write("        }\r\n");
      out.write("        .salary{\r\n");
      out.write("            left:620px;\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            top:130px;\r\n");
      out.write("            font-size:30px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"sidebar\">\r\n");
      out.write("        <sapn>\r\n");
      out.write("            <h1>导航</h1>\r\n");
      out.write("        </sapn>\r\n");
      out.write("        <span><a href=\"index\" style=\"color:white;text-decoration:none;\">首页</a></span>\r\n");
      out.write("        <span><a href=\"staffAdminister\" style=\"color:white;text-decoration:none;\">人事管理</a></span>\r\n");
      out.write("        <span><a href=\"attendanceCount\" style=\"color:white;text-decoration:none;\">考勤统计</a></span>\r\n");
      out.write("        <span style=\"background-color: #277de6\">工资管理</span>\r\n");
      out.write("        <span><a href=\"personalCenter\" style=\"color:white;text-decoration:none;\">个人中心</a></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <span id=\"function\">首页</span>\r\n");
      out.write("        <span id=\"function\">人事管理</span>\r\n");
      out.write("        <span id=\"function\">考勤统计</span>\r\n");
      out.write("        <span id=\"function\">工资管理</span>\r\n");
      out.write("        <span id=\"function\">个人中心</span>\r\n");
      out.write("        <span style=\"border-right: 0px;\">欢迎您，");
      out.print(name );
      out.write("</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <span><a id=\"choice1\" href=\"salaryAdminister\" class=\"p\" style=\"color:grey;text-decoration:none;background-color: rgb(222 232 244)\">计薪规则</a></span>\r\n");
      out.write("        <span><a id=\"choice2\" href=\"javascript:void(0);\" onclick=\"hide_table1()\" class=\"p\" style=\"color:grey;text-decoration:none;\">工资明细</a></span>\r\n");
      out.write("        <span><a id=\"choice3\" href=\"javascript:void(0);\" onclick=\"hide_table2()\" class=\"p\" style=\"color:grey;text-decoration:none;\">月工资单</a></span>\r\n");
      out.write("        \r\n");
      out.write("        <span id=\"title\">工资管理</span>\r\n");
      out.write("        <div id=\"lists1\" style=\"width:1000px;margin-left: 40px;margin-top: 35px;display:none\"><table id=\"list1\" style=\"width:1000px\"></table></div>\r\n");
      out.write("        <div id=\"lists2\" style=\"width:1000px;margin-left: 40px;margin-top: 35px;display:none\"><table id=\"list2\" style=\"width:1000px\"></table></div>\r\n");
      out.write("        <div id=\"salary_col\" class=\"salary\">工资=∑区域i工作时长*区域i工作单价</div>\r\n");
      out.write("        <div id=\"table\">\r\n");
      out.write("        <table class=\"table_p\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th class=\"th_p\">工作区域</th>\r\n");
      out.write("            <th class=\"th_p\">工资单价(/小时)</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"td_p\">区域1</td>\r\n");
      out.write("            <td class=\"td_p\">100</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"td_p\">区域2</td>\r\n");
      out.write("            <td class=\"td_p\">120</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class=\"td_p\">区域3</td>\r\n");
      out.write("            <td class=\"td_p\">150</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"tb1\">\r\n");
      out.write("            员工ID：<input id=\"s11\" class=\"easyui-textbox\" data-options=\"iconCls:'icon-search'\" style=\"width:300px\">\r\n");
      out.write("            月份：<input id=\"s12\" class=\"easyui-textbox\" data-options=\"iconCls:'icon-search'\" style=\"width:300px\">\r\n");
      out.write("            <button id=\"res1\">重置</button>\r\n");
      out.write("            <button id=\"sss1\">搜索</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"tb2\">\r\n");
      out.write("        员工ID：<input id=\"s21\" class=\"easyui-textbox\" data-options=\"iconCls:'icon-search'\" style=\"width:300px\">\r\n");
      out.write("        月份：<input id=\"s22\" class=\"easyui-textbox\" data-options=\"iconCls:'icon-search'\" style=\"width:300px\">\r\n");
      out.write("        <button id=\"res2\">重置</button>\r\n");
      out.write("        <button id=\"sss2\">搜索</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("//界面隐藏\r\n");
      out.write("    function hide_table1(){\r\n");
      out.write("    \tdocument.getElementById(\"choice1\").style.backgroundColor=\"\";\r\n");
      out.write("    \tdocument.getElementById(\"choice2\").style.backgroundColor=\"rgb(222 232 244)\";\r\n");
      out.write("    \tdocument.getElementById(\"choice3\").style.backgroundColor=\"\";\r\n");
      out.write("        document.getElementById(\"salary_col\").style.display=\"none\";\r\n");
      out.write("        document.getElementById(\"table\").style.display=\"none\";\r\n");
      out.write("        document.getElementById(\"lists2\").style.display=\"none\";\r\n");
      out.write("        document.getElementById(\"lists1\").style.display=\"\";\r\n");
      out.write("    }\r\n");
      out.write("    function hide_table2(){\r\n");
      out.write("    \tdocument.getElementById(\"choice1\").style.backgroundColor=\"\";\r\n");
      out.write("        document.getElementById(\"choice2\").style.backgroundColor=\"\";\r\n");
      out.write("        document.getElementById(\"choice3\").style.backgroundColor=\"rgb(222 232 244)\";\r\n");
      out.write("        document.getElementById(\"salary_col\").style.display=\"none\";\r\n");
      out.write("        document.getElementById(\"table\").style.display=\"none\";\r\n");
      out.write("        document.getElementById(\"lists1\").style.display=\"none\";\r\n");
      out.write("        document.getElementById(\"lists2\").style.display=\"\";\r\n");
      out.write("    }\r\n");
      out.write("//     搜索按钮\r\n");
      out.write("    $(\"#sss1\").click(function(){\r\n");
      out.write("        var s1 = $(\"#s11\").val();\r\n");
      out.write("        var s2 = $(\"#s12\").val();\r\n");
      out.write("        search1(s1,s2);\r\n");
      out.write("    });\r\n");
      out.write("    $(\"#sss2\").click(function(){\r\n");
      out.write("        var s1 = $(\"#s21\").val();\r\n");
      out.write("        var s2 = $(\"#s22\").val();\r\n");
      out.write("        search2(s1,s2);\r\n");
      out.write("    });\r\n");
      out.write("//     重置按钮\r\n");
      out.write("    $(\"#res1\").click(function(){\r\n");
      out.write("        $(\"#s11\").textbox('reset');\r\n");
      out.write("        $(\"#s21\").textbox('reset');\r\n");
      out.write("    });\r\n");
      out.write("    $(\"#res2\").click(function(){\r\n");
      out.write("        $(\"#s21\").textbox('reset');\r\n");
      out.write("        $(\"#s22\").textbox('reset');\r\n");
      out.write("    });\r\n");
      out.write("  \r\n");
      out.write("//   实现按照number和month条件搜索功能\r\n");
      out.write("    function search1(number,month) {\r\n");
      out.write("        $(function f1(){\r\n");
      out.write("            $(\"#list1\").datagrid({\r\n");
      out.write("                url:\"salaryConditionalSearch\",\r\n");
      out.write("                queryParams:{number:number,month:month},\r\n");
      out.write("                columns:[[\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"id\",\r\n");
      out.write("                        title:\"ID\",\r\n");
      out.write("                        width:100,\r\n");
      out.write("                        checkbox:true\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"number\",\r\n");
      out.write("                        title:\"员工ID\",\r\n");
      out.write("                        width:160\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"area1\",\r\n");
      out.write("                        title:\"区域1工资(元)\",\r\n");
      out.write("                        width:200\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"area2\",\r\n");
      out.write("                        title:\"区域2工资(元)\",\r\n");
      out.write("                        width:200\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"area3\",\r\n");
      out.write("                        title:\"区域3工资(元)\",\r\n");
      out.write("                        width:200\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"areaSum\",\r\n");
      out.write("                        title:\"总工资(元)\",\r\n");
      out.write("                        width:200\r\n");
      out.write("                    }\r\n");
      out.write("                ]],\r\n");
      out.write("                pagination:true,\r\n");
      out.write("                toolbar:\"#tb1\",\r\n");
      out.write("                //单击行不选中\r\n");
      out.write("                onClickRow: function (rowIndex, rowData) {\r\n");
      out.write("                    $(this).datagrid('unselectRow', rowIndex);\r\n");
      out.write("                },\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    $(function f1() {\r\n");
      out.write("        $(\"#list1\").datagrid({\r\n");
      out.write("            //url:后台数据查询的地址\r\n");
      out.write("            url: \"/salaryInformation\",\r\n");
      out.write("            //columns：填充的列数据\r\n");
      out.write("            //field:后台对象的属性\r\n");
      out.write("            //tille:列标题\r\n");
      out.write("            columns:[[\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"id\",\r\n");
      out.write("                        title:\"ID\",\r\n");
      out.write("                        width:100,\r\n");
      out.write("                        checkbox:true\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"number\",\r\n");
      out.write("                        title:\"员工ID\",\r\n");
      out.write("                        width:160\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"area1\",\r\n");
      out.write("                        title:\"区域1工资\",\r\n");
      out.write("                        width:200\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"area2\",\r\n");
      out.write("                        title:\"区域2工资\",\r\n");
      out.write("                        width:200\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"area3\",\r\n");
      out.write("                        title:\"区域3工资\",\r\n");
      out.write("                        width:200\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"areaSum\",\r\n");
      out.write("                        title:\"总工资\",\r\n");
      out.write("                        width:200\r\n");
      out.write("                    }\r\n");
      out.write("                ]],\r\n");
      out.write("            pagination:true,\r\n");
      out.write("            toolbar:\"#tb1\",\r\n");
      out.write("            //单击行不选中\r\n");
      out.write("            onClickRow: function (rowIndex, rowData) {\r\n");
      out.write("                $(this).datagrid('unselectRow', rowIndex);\r\n");
      out.write("            },\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("    function search2(number,month) {\r\n");
      out.write("        $(function f2(){\r\n");
      out.write("            $(\"#list2\").datagrid({\r\n");
      out.write("                url:\"salarySearch\",\r\n");
      out.write("                queryParams:{number:number,month:month},\r\n");
      out.write("                columns:[[\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"id\",\r\n");
      out.write("                        title:\"ID\",\r\n");
      out.write("                        width:100,\r\n");
      out.write("                        checkbox:true\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"number\",\r\n");
      out.write("                        title:\"员工ID\",\r\n");
      out.write("                        width:300\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"hours\",\r\n");
      out.write("                        title:\"小时\",\r\n");
      out.write("                        width:300\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"areaSum\",\r\n");
      out.write("                        title:\"总工资\",\r\n");
      out.write("                        width:300\r\n");
      out.write("                    }\r\n");
      out.write("                ]],\r\n");
      out.write("                pagination:true,\r\n");
      out.write("                toolbar:\"#tb2\",\r\n");
      out.write("                //单击行不选中\r\n");
      out.write("                onClickRow: function (rowIndex, rowData) {\r\n");
      out.write("                    $(this).datagrid('unselectRow', rowIndex);\r\n");
      out.write("                },\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    $(function f2() {\r\n");
      out.write("        $(\"#list2\").datagrid({\r\n");
      out.write("            //url:后台数据查询的地址\r\n");
      out.write("            url: \"/salaryInformation\",\r\n");
      out.write("            //columns：填充的列数据\r\n");
      out.write("            //field:后台对象的属性\r\n");
      out.write("            //tille:列标题\r\n");
      out.write("            columns:[[\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"id\",\r\n");
      out.write("                        title:\"ID\",\r\n");
      out.write("                        width:100,\r\n");
      out.write("                        checkbox:true\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"number\",\r\n");
      out.write("                        title:\"员工ID\",\r\n");
      out.write("                        width:300\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"hours\",\r\n");
      out.write("                        title:\"小时\",\r\n");
      out.write("                        width:300\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"areaSum\",\r\n");
      out.write("                        title:\"总工资\",\r\n");
      out.write("                        width:300\r\n");
      out.write("                    }\r\n");
      out.write("                ]],\r\n");
      out.write("            pagination:true,\r\n");
      out.write("            toolbar:\"#tb2\",\r\n");
      out.write("            //单击行不选中\r\n");
      out.write("            onClickRow: function (rowIndex, rowData) {\r\n");
      out.write("                $(this).datagrid('unselectRow', rowIndex);\r\n");
      out.write("            },\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
