/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2021-06-29 00:43:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class simulate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>打卡机模拟</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background-color: rgba(242, 242, 242, 1);\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            display: grid;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            place-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .head {\r\n");
      out.write("            width: 600px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .body {\r\n");
      out.write("            width: 600px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .input {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border: 1px solid grey;\r\n");
      out.write("            padding: 0.9rem 0.9rem;\r\n");
      out.write("            margin: 0.5rem auto;\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .input2 {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border: 1px solid grey;\r\n");
      out.write("            padding: 0.9rem 0.9rem;\r\n");
      out.write("            margin: 0.5rem auto;\r\n");
      out.write("            width: 320px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn {\r\n");
      out.write("            background-color: rgba(204, 204, 204, 1);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            border: 1px solid rgba(204, 204, 204, 1);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            letter-spacing: 0.1rem;\r\n");
      out.write("            padding: 0.9rem 6rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background-color: #277de6;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form>.btn {\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"head\">\r\n");
      out.write("        <h1>考勤打卡模拟界面</h1>\r\n");
      out.write("        <hr class=\"line\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"body\">\r\n");
      out.write("        <form action=\"/uploadAttendance\" method=\"POST\" class=\"form\" id=\"form1\" name=\"form1\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"员工ID\" class=\"input\" name=\"number\" />\r\n");
      out.write("            <select class=\"input\" name=\"machineID\" style=\"width: 430px;\">\r\n");
      out.write("                <option value =\"1\">1号机</option>\r\n");
      out.write("                <option value =\"2\">2号机</option>\r\n");
      out.write("                <option value=\"3\">3号机</option>\r\n");
      out.write("                <option value=\"4\">4号机</option>\r\n");
      out.write("                <option value=\"5\">5号机</option>\r\n");
      out.write("                <option value=\"6\">6号机</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            <div class=\"time1\">\r\n");
      out.write("                签到时间：<input type=\"time\" class=\"input2\" placeholder=\"dfsd\" name=\"startTime\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"time2\">\r\n");
      out.write("                签退时间：\r\n");
      out.write("                <input type=\"time\" class=\"input2\" name=\"endTime\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"button\" class=\"btn\" onclick=\"check()\" value=\"打卡\" />\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function check() {\r\n");
      out.write("            const firstForm = document.getElementById(\"form1\");\r\n");
      out.write("            firstForm.submit();\r\n");
      out.write("            alert(\"打卡成功\");\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
