/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2021-06-27 13:16:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gx.domain.*;

public final class staffAdminister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.gx.domain");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>人事管理</title>\r\n");
      out.write("\r\n");

User user = (User) request.getSession().getAttribute("user"); 
String name = user.getName();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 导入easyui的资源文件 -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/jquery.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"static/easyui/themes/icon.css\">\r\n");
      out.write("        <link id=\"themeLink\" rel=\"stylesheet\" type=\"text/css\" href=\"static/easyui/themes/default/easyui.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"static/css/zTreeStyle/zTreeStyle.css\">\r\n");
      out.write("        <script src=\"static/js/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #sidebar {\r\n");
      out.write("            background-color: #000;\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 750px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin: 15px 0px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #sidebar span {\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 5px 0px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            line-height: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #header {\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background-color: #277de6;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #header span {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            float: left;\r\n");
      out.write("            border: 1.5px solid grey;\r\n");
      out.write("            width: 210px;\r\n");
      out.write("            height: 37px;\r\n");
      out.write("            line-height: 37px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #function:hover {\r\n");
      out.write("            background: #8f949a;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #content {\r\n");
      out.write("            float:left;\r\n");
      out.write("            display:block;\r\n");
      out.write("            width:1275px;\r\n");
      out.write("            height:710px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #content #title{\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("            font-size: 26px;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("            margin-left: 15px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        #lists {\r\n");
      out.write("            display:block;\r\n");
      out.write("            width:1000px;\r\n");
      out.write("            margin-left: 40px;\r\n");
      out.write("            margin-top: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #win hr {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"sidebar\">\r\n");
      out.write("        <sapn>\r\n");
      out.write("            <h1>导航</h1>\r\n");
      out.write("        </sapn>\r\n");
      out.write("        <span><a href=\"index\" style=\"color:white;text-decoration:none;\">首页</a></span>\r\n");
      out.write("        <span style=\"background-color: #277de6\">人事管理</span>\r\n");
      out.write("        <span><a href=\"attendanceCount\" style=\"color:white;text-decoration:none;\">考勤统计</a></span>\r\n");
      out.write("        <span><a href=\"salaryAdminister\" style=\"color:white;text-decoration:none;\">工资管理</a></span>\r\n");
      out.write("        <span><a href=\"personalCenter\" style=\"color:white;text-decoration:none;\">个人中心</a></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <span id=\"function\">首页</span>\r\n");
      out.write("        <span id=\"function\">人事管理</span>\r\n");
      out.write("        <span id=\"function\">考勤统计</span>\r\n");
      out.write("        <span id=\"function\">工资管理</span>\r\n");
      out.write("        <span id=\"function\">个人中心</span>\r\n");
      out.write("        <span style=\"border-right: 0px;\">欢迎您，");
      out.print(name );
      out.write("</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <span id=\"title\">人事管理</span>\r\n");
      out.write("        <div id=\"lists\"><table id=\"list\"></table></div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- 工具条 -->\r\n");
      out.write("        <div id=\"tb\">\r\n");
      out.write("            <a id=\"addBtn\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add',plain:true\">添加</a>\r\n");
      out.write("            <a id=\"deletebanchesBtn\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-remove',plain:true\">批量删除</a>\r\n");
      out.write("<!--            </div> -->\r\n");
      out.write("            员工ID：<input id=\"s1\" class=\"easyui-textbox\" data-options=\"iconCls:'icon-search'\" style=\"width:300px\">\r\n");
      out.write("            员工姓名：<input id=\"s2\" class=\"easyui-textbox\" data-options=\"iconCls:'icon-search'\" style=\"width:300px\">\r\n");
      out.write("            <button id=\"res\">重置</button>\r\n");
      out.write("            <button id=\"sss\">搜索</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("         <!-- 编辑保存窗口 -->\r\n");
      out.write("        <div id=\"win\" class=\"easyui-window\" title=\"员工数据编辑\" style=\"width:800px;height:400px\" data-options=\"iconCls:'icon-save',modal:true,closed:true\"> \r\n");
      out.write("            <form method=\"post\" id=\"editForm\"> \r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <input type=\"hidden\" name=\"id\">\r\n");
      out.write("                员工ID：<input type=\"text\" name=\"number\" class=\"easyui-validatebox\" data-options=\"required:true\"/><br/> \r\n");
      out.write("                用户姓名：<input type=\"text\" name=\"name\" class=\"easyui-validatebox\" data-options=\"required:true\"/><br/> \r\n");
      out.write("                年龄：<input type=\"text\" name=\"age\" class=\"easyui-validatebox\" data-options=\"required:true\"/><br/> \r\n");
      out.write("                工资级别：<input type=\"text\" name=\"salaryLevel\" class=\"easyui-validatebox\" data-options=\"required:true\"/><br/> \r\n");
      out.write("                身体状况：<input type=\"text\" name=\"bodyStatus\" class=\"easyui-validatebox\" data-options=\"required:true\"/><br/> \r\n");
      out.write("                家庭地址：<input type=\"text\" name=\"address\" class=\"easyui-validatebox\" data-options=\"required:true\"/><br/> \r\n");
      out.write("                联系方式：<input type=\"text\" name=\"phone\" class=\"easyui-validatebox\" data-options=\"required:true\"/><br/> \r\n");
      out.write("                <a id=\"saveBtn\" href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save'\">保存</a> \r\n");
      out.write("            </form>            \r\n");
      out.write("        </div>       \r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("//     搜索按钮\r\n");
      out.write("    $(\"#sss\").click(function(){\r\n");
      out.write("        var s1 = $(\"#s1\").val();\r\n");
      out.write("        var s2 = $(\"#s2\").val();\r\n");
      out.write("        search(s1,s2);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("//     重置按钮\r\n");
      out.write("    $(\"#res\").click(function(){\r\n");
      out.write("        $(\"#s1\").textbox('reset');\r\n");
      out.write("        $(\"#s2\").textbox('reset');\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("  //保存数据\r\n");
      out.write("    $(\"#saveBtn\").click(function(){\r\n");
      out.write("        $(\"#editForm\").form(\"submit\",{\r\n");
      out.write("            //url: 提交到后台的地址\r\n");
      out.write("            url:\"saveStaffInformation\",\r\n");
      out.write("            //onSubmit: 表单提交前的回调函数，true：提交表单   false：不提交表单\r\n");
      out.write("            onSubmit:function(){\r\n");
      out.write("                //判断表单的验证是否都通过了\r\n");
      out.write("                return $(\"#editForm\").form(\"validate\");\r\n");
      out.write("            },\r\n");
      out.write("            //success:服务器执行完毕回调函数\r\n");
      out.write("            success:function(data){ //data: 服务器返回的数据，类型字符串类\r\n");
      out.write("                //要求Controller返回的数据格式：  \r\n");
      out.write("                //成功：{success:true} 失败:{success:false,msg:错误信息}\r\n");
      out.write("                \r\n");
      out.write("                //把data字符串类型转换对象类型\r\n");
      out.write("                data = eval(\"(\"+data+\")\");\r\n");
      out.write("                \r\n");
      out.write("                if(data.success){\r\n");
      out.write("                    //关闭窗口\r\n");
      out.write("                    $(\"#win\").window(\"close\");\r\n");
      out.write("                    //刷新datagrid\r\n");
      out.write("                    $(\"#list\").datagrid(\"reload\");\r\n");
      out.write("                    \r\n");
      out.write("                    $.messager.alert(\"提示\",\"保存成功\",\"info\");\r\n");
      out.write("                }else{\r\n");
      out.write("                    $.messager.alert(\"提示\",\"保存失败：\"+data.msg,\"error\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("  \r\n");
      out.write("  //打开编辑窗口\r\n");
      out.write("    $(\"#addBtn\").click(function(){ \r\n");
      out.write("        $(\"#win\").window(\"open\"); \r\n");
      out.write("        });\r\n");
      out.write("  \r\n");
      out.write("//   实现多条件搜索功能\r\n");
      out.write("    function search(number, name) {\r\n");
      out.write("        $(function(){\r\n");
      out.write("            $(\"#list\").datagrid({\r\n");
      out.write("                url:\"staffConditionalSearch\",\r\n");
      out.write("                queryParams:{number:number, name:name},\r\n");
      out.write("                columns:[[\r\n");
      out.write("                \t{\r\n");
      out.write("                        field:\"id\",\r\n");
      out.write("                        title:\"ID\",\r\n");
      out.write("                        width:100,\r\n");
      out.write("                        checkbox:true\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"number\",\r\n");
      out.write("                        title:\"员工ID\",\r\n");
      out.write("                        width:120\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"name\",\r\n");
      out.write("                        title:\"员工姓名\",\r\n");
      out.write("                        width:120\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                    \tfield:\"age\",\r\n");
      out.write("                    \ttitle:\"年龄\",\r\n");
      out.write("                    \twidth:50\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"salaryLevel\",\r\n");
      out.write("                        title:\"工资级别\",\r\n");
      out.write("                        width:80\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"bodyStatus\",\r\n");
      out.write("                        title:\"身体状况\",\r\n");
      out.write("                        width:80\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"address\",\r\n");
      out.write("                        title:\"家庭地址\",\r\n");
      out.write("                        width:150\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"phone\",\r\n");
      out.write("                        title:\"手机号\",\r\n");
      out.write("                        width:120\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"operate\",\r\n");
      out.write("                        title:\"操作\",\r\n");
      out.write("                        width:200,\r\n");
      out.write("                        align:\"center\",\r\n");
      out.write("                        formatter:function(value, row, index){\r\n");
      out.write("                            var str = '<a href=\"#\" name=\"editBtn\" class=\"easyui-linkbutton\" onclick=\"edit(\\''+ index +'\\')\"></a>'\r\n");
      out.write("                            var str2 = '<a href=\"#\" name=\"deleteBtn\" class=\"easyui-linkbutton\" onclick=\"del(\\''+ index +'\\')\"></a>'\r\n");
      out.write("                            return str+str2;\r\n");
      out.write("                        }           \r\n");
      out.write("                    }\r\n");
      out.write("                ]],\r\n");
      out.write("                pagination:true,\r\n");
      out.write("                toolbar:\"#tb\",\r\n");
      out.write("                //单击行不选中\r\n");
      out.write("                onClickRow: function (rowIndex, rowData) {\r\n");
      out.write("                    $(this).datagrid('unselectRow', rowIndex);\r\n");
      out.write("                },\r\n");
      out.write("                //加载操作列按钮图标\r\n");
      out.write("                onLoadSuccess:function(data){\r\n");
      out.write("                    $(\"a[name='editBtn']\").linkbutton({\r\n");
      out.write("                        text:\"修改\",\r\n");
      out.write("                        plain:true,\r\n");
      out.write("                        iconCls:\"icon-edit\",\r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                    $(\"a[name='deleteBtn']\").linkbutton({\r\n");
      out.write("                        text:\"删除\",\r\n");
      out.write("                        plain:true,\r\n");
      out.write("                        iconCls:\"icon-remove\",\r\n");
      out.write("                    });\r\n");
      out.write("                },\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("  //修改回显\r\n");
      out.write("    function edit(index){   \r\n");
      out.write("        var page = $('#list').datagrid('options').pageNumber; //获取页数\r\n");
      out.write("        index=Number(index)+Number((page-1)*10);\r\n");
      out.write("        var rows = $(\"#list\").datagrid(\"getRows\");\r\n");
      out.write("        var row = rows[index];\r\n");
      out.write("        $(\"#editForm\").form(\"load\",\"findStaffById?id=\"+row.id);\r\n");
      out.write("        $(\"#win\").window(\"open\");\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("  //删除操作\r\n");
      out.write("    function del(index){ \r\n");
      out.write("    \tvar page = $('#list').datagrid('options').pageNumber; //获取页数\r\n");
      out.write("        index=Number(index)+Number((page-1)*10);\r\n");
      out.write("        var rows = $(\"#list\").datagrid(\"getRows\");\r\n");
      out.write("        var row = rows[index];\r\n");
      out.write("        $.messager.confirm(\"提示\",\"确认删除数据吗?\",function(value){\r\n");
      out.write("            if(value){      \r\n");
      out.write("                $.post(\"deleteOneStaff\",{\"index\":row.id},function(data){\r\n");
      out.write("                    if(data.success){ \r\n");
      out.write("                        //刷新 datagrid \r\n");
      out.write("                        $(\"#list\").datagrid(\"reload\"); \r\n");
      out.write("                        $.messager.alert(\"提示\",\"删除成功\",\"info\");\r\n");
      out.write("                    }\r\n");
      out.write("                    else{\r\n");
      out.write("                        $.messager.alert(\"提示\",\"删除失败： \"+data.msg,\"error\");\r\n");
      out.write("                    }\r\n");
      out.write("                },\"json\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("      }\r\n");
      out.write("  \r\n");
      out.write("    $(function() {\r\n");
      out.write("        $(\"#list\").datagrid({\r\n");
      out.write("            //url:后台数据查询的地址\r\n");
      out.write("            url: \"/staffInformation\",\r\n");
      out.write("            //columns：填充的列数据\r\n");
      out.write("            //field:后台对象的属性\r\n");
      out.write("            //tille:列标题\r\n");
      out.write("            columns:[[\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"id\",\r\n");
      out.write("                        title:\"ID\",\r\n");
      out.write("                        width:100,\r\n");
      out.write("                        checkbox:true\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"number\",\r\n");
      out.write("                        title:\"员工ID\",\r\n");
      out.write("                        width:120\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"name\",\r\n");
      out.write("                        title:\"员工姓名\",\r\n");
      out.write("                        width:120\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"age\",\r\n");
      out.write("                        title:\"年龄\",\r\n");
      out.write("                        width:50\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"salaryLevel\",\r\n");
      out.write("                        title:\"工资级别\",\r\n");
      out.write("                        width:80\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"bodyStatus\",\r\n");
      out.write("                        title:\"身体状况\",\r\n");
      out.write("                        width:80\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"address\",\r\n");
      out.write("                        title:\"家庭地址\",\r\n");
      out.write("                        width:150\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"phone\",\r\n");
      out.write("                        title:\"手机号\",\r\n");
      out.write("                        width:120\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        field:\"operate\",\r\n");
      out.write("                        title:\"操作\",\r\n");
      out.write("                        width:200,\r\n");
      out.write("                        align:\"center\",\r\n");
      out.write("                        formatter:function(value, row, index){\r\n");
      out.write("                            var str = '<a href=\"#\" name=\"editBtn\" class=\"easyui-linkbutton\" onclick=\"edit(\\''+ index +'\\')\"></a>'\r\n");
      out.write("                            var str2 = '<a href=\"#\" name=\"deleteBtn\" class=\"easyui-linkbutton\" onclick=\"del(\\''+ index +'\\')\"></a>'\r\n");
      out.write("                            return str+str2;\r\n");
      out.write("                        }           \r\n");
      out.write("                    }\r\n");
      out.write("                ]],\r\n");
      out.write("            pagination:true,\r\n");
      out.write("            toolbar:\"#tb\",\r\n");
      out.write("            //单击行不选中\r\n");
      out.write("            onClickRow: function (rowIndex, rowData) {\r\n");
      out.write("                $(this).datagrid('unselectRow', rowIndex);\r\n");
      out.write("            },\r\n");
      out.write("            //加载操作列按钮图标\r\n");
      out.write("            onLoadSuccess:function(data){\r\n");
      out.write("                $(\"a[name='editBtn']\").linkbutton({\r\n");
      out.write("                    text:\"修改\",\r\n");
      out.write("                    plain:true,\r\n");
      out.write("                    iconCls:\"icon-edit\",\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\"a[name='deleteBtn']\").linkbutton({\r\n");
      out.write("                    text:\"删除\",\r\n");
      out.write("                    plain:true,\r\n");
      out.write("                    iconCls:\"icon-remove\",\r\n");
      out.write("                });\r\n");
      out.write("            },\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //批量删除\r\n");
      out.write("        $(\"#deletebanchesBtn\").click(function(){\r\n");
      out.write("                    var rows =$(\"#list\").datagrid(\"getSelections\");\r\n");
      out.write("                    if(rows.length==0){\r\n");
      out.write("                        $.messager.alert(\"提示\",\"删除操作至少选择一行\",\"warning\");\r\n");
      out.write("                        return;\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //格式： id=1&id=2&id=3\r\n");
      out.write("                    $.messager.confirm(\"提示\",\"确认删除数据吗?\",function(value){\r\n");
      out.write("                        if(value){\r\n");
      out.write("                            var idStr = \"\";\r\n");
      out.write("                            //遍历数据\r\n");
      out.write("                            $(rows).each(function(i){\r\n");
      out.write("                                idStr+=(\"id=\"+rows[i].id+\"&\");\r\n");
      out.write("                            });\r\n");
      out.write("                            idStr = idStr.substring(0,idStr.length-1);\r\n");
      out.write("                            \r\n");
      out.write("                            //传递到后台\r\n");
      out.write("                            $.post(\"deleteManyStaffs\",idStr,function(data){\r\n");
      out.write("                                if(data.success){\r\n");
      out.write("                                    //刷新datagrid\r\n");
      out.write("                                    $(\"#list\").datagrid(\"reload\");\r\n");
      out.write("                                    \r\n");
      out.write("                                    $.messager.alert(\"提示\",\"删除成功\",\"info\");\r\n");
      out.write("                                }else{\r\n");
      out.write("                                    $.messager.alert(\"提示\",\"删除失败：\"+data.msg,\"error\");\r\n");
      out.write("                                }\r\n");
      out.write("                            },\"json\");\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
